services:
  db:
    image: pgvector/pgvector:pg16
    container_name: db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: ./api
    container_name: api
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://app:app@db:5432/appdb
      REDIS_URL: redis://redis:6379/0   # ✅ fix
      JWT_SECRET: supersecretkey
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

volumes:
  db_data:
