# Context Auto-Discovery Configuration
#
# This file configures which directories and files the auto-discovery agent
# will scan to find relevant context for module discovery.

# Directories to scan for relevant context documents
directories_to_scan:
  - ./docs/
  - ./docs/design/
  - ./docs/modules/ai-development/
  - ./.dev/
  # Add your custom paths below:
  # - ~/meeting-notes/
  # - ~/slack-exports/
  # - ~/Documents/project-planning/

# File patterns to include in scan
file_patterns:
  - "*.md"
  - "*.txt"
  - "*.pdf"
  - "*.doc"
  - "*.docx"

# Patterns to exclude from scan
exclude_patterns:
  - "node_modules/"
  - ".git/"
  - ".obsidian/"
  - "build/"
  - "dist/"
  - "*.log"
  - "package-lock.json"
  - ".env"
  - "*.lock"

# Content categories to identify
# Auto-discovery will categorize each document into these buckets
categories:
  vision:         # What we're building and why (strategy, goals, purpose)
    enabled: true
    keywords:
      - "vision"
      - "strategy"
      - "why we're building"
      - "goals"
      - "mission"

  requirements:   # What the system must do (functional/non-functional requirements)
    enabled: true
    keywords:
      - "requirements"
      - "must have"
      - "user stories"
      - "features"
      - "capabilities"

  technical:      # How to build it (architecture, tech discussions, design)
    enabled: true
    keywords:
      - "architecture"
      - "technical design"
      - "implementation"
      - "technology stack"
      - "database"
      - "API"

  constraints:    # Limits and boundaries (budget, timeline, expertise, platform)
    enabled: true
    keywords:
      - "budget"
      - "timeline"
      - "deadline"
      - "constraints"
      - "limitations"
      - "team size"

  decisions:      # Choices already made (technology selections, approaches chosen)
    enabled: true
    keywords:
      - "decided"
      - "chosen"
      - "selected"
      - "we're using"
      - "we will use"

# Auto-discovery behavior settings
auto_discovery_settings:
  # Maximum files to include per category
  max_files_per_category: 10

  # Minimum relevance score (0.0 - 1.0) for a file to be included
  # Higher = more selective, Lower = more inclusive
  min_relevance_score: 0.5

  # Include content excerpts in intake.md?
  include_excerpts: true

  # Length of excerpts (characters)
  excerpt_length: 500

  # Generate summaries for each document?
  generate_summaries: true

  # Identify contradictions between sources?
  detect_contradictions: true

  # Consolidate decisions from multiple sources?
  consolidate_decisions: true

# Advanced options
advanced:
  # Follow file references (e.g., "see architecture.md")?
  follow_references: true

  # Maximum depth for reference following
  max_reference_depth: 2

  # Include Git commit messages for context?
  include_git_history: false

  # Scan issues/PRs if in a git repo?
  scan_git_issues: false
